matrix:
  include:
    - language: bash
      script:
        ./downloadData.sh
    - language: python
      python: "3.6"
      install:
        - pip install pipenv
        - pipenv install
      script:
        - python main.py --test all --meld false