language: python
sudo: required
python: "3.6"
install:
  - pip install pipenv
  - pipenv install
  - cd scripts
  - chmod +x do
  - ./do download-test-data
  - cd ..
script:
  - coverage run test.py all
after_script:
  - coverage report